<html>

<head>
    <title>backend</title>
    <meta http-equiv="Content-type: text/html; charset=utf-8">
    <style>
        body {
            font-family: verdana, arial, helvetica, sans-serif;
            font-size: 14px;
        }
        a.normal { text-decoration: none; font-weight: normal; }
        a.normal:link  { color: #000000; }
        a.normal:visited  { color: #000000; }
        a.normal:hover  { color: #0000ff; }
        a.normal:active  { color: #000000; }

        .normaltext { color: #000000; font-weight: normal; font-size: 14px; }
        table.normaltext td {font-weight: normal; font-size: 14px; }
        .cell_event { background-color: #fd9; cursor: default; }
        .cell_fixed { background-color: #f66; cursor: default; }
        .cellnow	{ background-color: #000; cursor: default; }
    </style>
</head>

<body>

<div id="content">


<table border="0" cellpadding="4" cellspacing="4">
    <tr>
        <td align="center">
            <div style="width:311px; border: 1px solid #000; padding: 3px;"> <b><?=$daylong?>, <?=$monthlong?> <?=$today?>, <?=$year?></b> </div>
        </td>

        <td valign="middle" align="center">&nbsp;</td>
    </tr>

    <!-- EVENT EDIT FORM -->
    <tr>
        <td valign="top">
            <table border="1" cellpadding="4" cellspacing="1" width="100%" height="445">
                <tr>
                    <td class="eventControl" valign="top">
                        <form name="jcal_post" action="" method="post" id="event-form">
                            <input type="hidden" id="action" name="action" value="">

                            <b>Event title</b>
                            <br>
                            <input type="text" name="day_title" value="<?=$eventTitle?>" size="40" maxlength="30">
                            <br><br>
                            <b>Event Description</b>
                            <br>
                            <textarea name="day_event" cols="40" rows="14"><?=$eventDesc?></textarea>
                            <!-- NEW WORKS - with date field -->
                            <input type="hidden" value="<?=$year?>-<?=$month?>-<?=$today?>" name="date">
                            <br>
                            <br>

                            <input type="hidden"   name="fixed_event" value="0">
                            <input type="checkbox" name="fixed_event" value="1"<?=($isFixedEvent == 1) ? ' checked="checked"':''?>> High priority!<br>
                            <br>
                            <input type="submit" class="button" value="Add/Update this event" onclick="document.getElementById('action').setAttribute('value', 'add'); return true;"><br>
                            <input type="submit" class="button" value="Delete this event" onclick="if( confirm('Are you sure to delete this event?') ) { document.getElementById('action').setAttribute('value', 'delete'); return true; }">
                        </form>

                    </td>
                </tr>
            </table>
        </td>
        <!-- END OF EVENT EDIT FORM -->

        <!-- CALENDAR VIEW -->
        <td valign="top">

            <div class="calendar backendCalendar">

                <table border="0" width="230" class="calendar_table">
                    <!-- ROW 1 -->
                    <tr>
                        <!-- SELECT YEAR -->
                        <td valign="middle" align="center">
                            <table  class="year_table">
                                <tr>
                                    <td>
                                        <a href="?date=<?=$lastYear?>-<?=$month?>-<?=$today?>"><div class="prev_year"> <- </div></a>
                                    </td>
                                    <td class="year_text_left">&nbsp;</td>
                                    <td valign="middle" class="today_year"><b><?=$year?></b></div></td>
                                    <td class="year_text_right">&nbsp;</td>
                                    <td>
                                        <a href="?date=<?=$nextYear?>-<?=$month?>-<?=$today?>"><div class="next_year"> -> </div></a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                        <!-- END OF SELECT YEAR -->
                    </tr>
                    <!-- END ROW 1 -->

                    <!-- ROW 2 -->
                    <tr>
                        <!-- SELECT MONTH -->
                        <td valign="top">

                            <table border="1" cellpadding="1" cellspacing="0" width="230">
                                <tr>
                                    <?php for ($i = 0; $i < 12; $i++) { ?>
                                        <?php $monthNum = sprintf("%02d", $i+1);?>

                                        <td valign="middle" class="month_cell cell<?= ($month == $monthNum) ? ' selected_month' :''?>">
                                            <a href="?date=<?=$year?>-<?=$monthNum?>-01" class="normal"><?= $monthNames[$i] ?></a>
                                        </td>

                                        <?php if ($i == 5) { echo "</tr>\n<tr>"; } ?>
                                    <?php } ?>
                                </tr>
                            </table>
                            <!-- END OF SELECT MONTH -->
                            <br>
                        </td>
                    </tr>

                </table>

                <!-- display name of month -->
                <table border="1" cellpadding="2" cellspacing="0" width="230" class="normaltext">
                    <tr>
                        <td class="cell" colspan="7" valign="middle" align="center">
                            <span class="regheading"><b><?=$currentMonth?></b></span>
                        </td>
                    </tr>
                    <tr>
                        <!-- display day names -->
                        <?php foreach ($dayNames as $value) { ?>
                            <td class="cell" valign="middle" width="10%">
                                <span class="normaltext"><b><?=$value?></b></span>
                            </td>
                        <?php } ?>
                    </tr>
                    <tr>

                        <!-- display days -->
                        <?php
                        $counter = 0;

                        foreach ($daysArray as $day) { ?>

                            <?php if (is_null($day)) { ?>
                                <!-- display blank days as nbsp's -->
                                <td class="cell_empty" valign="middle">
                                    <span class="normaltext">&nbsp;</span>
                                </td>
                            <?php } else {
                                $currentDay = "$year-$month-$day";
                                if ($counter > 6) {
                                    echo "\n</tr>\n<tr>\n";
                                    $counter = 0;
                                }
                                ?>

                                <!-- //search for event on this day and mark cell if title not empty -->
                                <?php if (isset($eventTitles[$currentDay])) { ?>
                                    <?php $event = $eventTitles[$currentDay]; ?>
                                    <td valign="middle" title="<?=htmlspecialchars($event['title'])?><?= !empty($event['event']) ? ' / ' . htmlspecialchars($event['event']) : '';?>"
                                        data-date="<?=$currentDay?>"
                                        class="day_cell <?= ($event['fixed'] == 1) ? ' cell_fixed' :'';?> cell_event<?= ($currentDay == $todayDate) ? ' celltoday':'';?>">
                                        <a href="?date=<?=$currentDay?>" class="normal"><?=$day?></a>
                                    </td>
                                <?php } else { ?>
                                    <!-- //show default cell style for day -->
                                    <td valign="middle" data-date="<?=$currentDay?>"
                                        class="day_cell cell<?=($currentDay == $todayDate) ? ' celltoday':''?>">
                                        <a href="?date=<?=$currentDay?>" class="normal"><?=$day?></a>
                                    </td>
                                <?php } ?>

                            <?php } ?>
                            <!-- /display days -->

                            <?php $counter++; ?>
                        <?php } ?>


                    </tr>
                    <!-- END ROW 2 -->
                </table>

                <br />
                <br />
                <a href="?date=<?=date('Y-m-d')?>" class="normal">Jump to Today</a>

            </div>

        </td>

    </tr>
</table>


<!-- end outer table -->
</td>
</tr>
</table>



</div>
<!-- end div content -->


</body>
</html>