<html>

<head>
    <title>frontend</title>
    <meta http-equiv="Content-type: text/html; charset=utf-8">
    <style>
        body {
            font-family: verdana, arial, helvetica, sans-serif;
            font-size: 14px;
        }
        a.normal { text-decoration: none; font-weight: normal; }
        a.normal:link  { color: #000000; }
        a.normal:visited  { color: #000000; }
        a.normal:hover  { color: #0000ff; }
        a.normal:active  { color: #000000; }

        .normaltext { color: #000000; font-weight: normal; font-size: 14px; }
        table.normaltext td {font-weight: normal; font-size: 14px; }
        .cell_event { background-color: #fd9; cursor: default; }
        .cell_fixed { background-color: #f66; cursor: default; }
        .cellnow	{ background-color: #000; cursor: default; }
    </style>
</head>

<body>

<div id="content">

    <table>
        <tr>
            <td valign="top">

                <div class="calendar">

                    <table border="0" width="300" class="calendar_table">
                        <tr>
                            <!-- SELECT YEAR -->
                            <td valign="middle" align="center">
                                <table class="year_table">
                                    <tr>
                                        <td valign="middle">
                                            <a href="<?=SITE_URL?>/index.php?date=<?=$lastYear?>-<?=$month?>-<?=$today?>" class="normal"><div class="prev_year"> <- </div></a>
                                        </td>
                                        <td class="year_text_left">&nbsp;</td>
                                        <td valign="middle" class="today_year"><b><?=$year?></b></td>
                                        <td class="year_text_right">&nbsp;</td>
                                        <td valign="middle">
                                            <a href="<?=SITE_URL?>/index.php?date=<?=$nextYear?>-<?=$month?>-<?=$today?>" class="normal"><div class="next_year"> -> </div></a>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <!-- END OF SELECT YEAR -->
                        </tr>
                        <tr>
                            <!-- SELECT MONTH -->
                            <td valign="top">

                                <table border="1" cellpadding="1" cellspacing="0" width="300">
                                    <tr>
                                        <?php for ($i = 0; $i < 12; $i++) { ?>
                                            <?php $currentIndex = $i; ?>
                                            <?php $monthNum = sprintf("%02d", $i+1);?>

                                            <td valign="middle" class="month_cell cell<?= ($month == $monthNum) ? ' selected_month' :''?>"> <a href="<?=SITE_URL?>/index.php?date=<?=$year?>-<?=$monthNum?>-01" class="normal"><?= $monthNames[$currentIndex] ?></a> </td>

                                            <?php if ($currentIndex == 5) { echo "</tr>\n<tr>"; } ?>
                                        <?php } ?>
                                    </tr>
                                </table>
                                <!-- END OF SELECT MONTH -->
                                <br>


                                <!-- display name of month -->
                                <table border="1" cellpadding="2" cellspacing="0" width="300" class="normaltext">
                                    <tr>
                                        <td class="cell" colspan="7" valign="middle" align="center">
                                            <span class="regheading"><b><?=$currentMonth?></b></span>
                                        </td>
                                    </tr>

                                    <tr>

                                        <!-- display day names -->
                                        <?php foreach ($dayNames as $value) { ?>
                                            <td class="cell" valign="middle" width="10%">
                                                <span class="normaltext"><b><?=$value?></b></span>
                                            </td>
                                        <?php } ?>
                                    </tr>
                                    <tr>

                                        <!-- display days -->
                                        <?php
                                        $counter = 0;

                                        foreach ($daysArray as $day) { ?>

                                            <?php if (is_null($day)) { ?>
                                                <!-- display blank days as nbsp's -->
                                                <td class="cell_empty" valign="middle">
                                                    <span class="normaltext">&nbsp;</span>
                                                </td>
                                            <?php } else {
                                                $currentDay = "$year-$month-$day";
                                                if ($counter > 6) {
                                                    echo "\n</tr>\n<tr>\n";
                                                    $counter = 0;
                                                }
                                                ?>

                                                <!-- //search for event on this day and mark cell if title not empty -->
                                                <?php if (isset($eventTitles[$currentDay])) { ?>
                                                    <?php $event = $eventTitles[$currentDay]; ?>
                                                    <td valign="middle" title="<?=htmlspecialchars($event['title']);?><?= !empty($event['event']) ? ' / ' . htmlspecialchars($event['event']) : '';?>" class="day_cell <?= ($event['fixed'] == 1) ? ' cell_fixed' :'';?> cell_event<?= ($currentDay == $todayDate) ? ' celltoday':'';?>">
                                                        <?=$day?>
                                                    </td>
                                                <?php } else { ?>
                                                    <!-- //show default cell style for day -->
                                                    <td valign="middle" class="day_cell cell<?=($currentDay == $todayDate) ? ' celltoday':''?>">
                                                        <?=$day?>
                                                    </td>
                                                <?php } ?>

                                            <?php } ?>
                                            <!-- /display days -->

                                        <?php $counter++; ?>
                                        <?php } ?>

                                    </tr>
                                </table>

                                <!-- end outer table -->
                            </td>
                        </tr>
                    </table>

                    </div>

                </td>
                <td valign="top">
                    <div class="list">
                        <?php
                        foreach ($eventTitles as $date => $event) { ?>
                            <div style="border-bottom: #999 1px solid">
                                <b><?=$date?> - <?=$event['title']?></b><br />
                                <span><?=$event['event']?></span>
                            </div>
                        <?php } ?>
                    </div>
                </td>
            </tr>
        </table>

</div>

</body>
</html>